# from asyncio.windows_events import NULL
# from types import NoneType
# import webbrowser

# urlstart        = 'https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch?'
# apikey          = config.get_yahoo_shop_key()
# query           = 'soup'
# affiliate_type  = ''
# affiliate_id    = ''


# def add_filter(filter, value):
#     return filter + '=' + value + '&'

# url = urlstart + add_filter('appid', apikey) + add_filter('query',query)
# # url = urlstart + 'appid=' + apikey + '&' + add_filter(query)

# webbrowser.open(url, new = 0, autoraise = True)


# shopping requests

# https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch?
    # appid              = dj00aiZpPW42bWdCR2x5NEhFNyZzPWNvbnN1bWVyc2VjcmV0Jng9Y2Q-
    # &genre_category_id = 635
    # &sort              = -sold

# https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch?appid=dj00aiZpPW42bWdCR2x5NEhFNyZzPWNvbnN1bWVyc2VjcmV0Jng9Y2Q-&query=soup&






# {
#     "totalResultsAvailable": 2091806,
#     "totalResultsReturned": 20,
#     "firstResultsPosition": 1,
#     "request": { "query": "" },
#     "hits": [
#         {
#             "index": 1,
#             "name": "最新型　第3世代　fire TV stick　ファイヤースティックTV　Alexa対応音声認識リモコン　 youtube abema",
#             "description": "同梱内容<br>FIRE TV stick x1<br>電源アダプター　x1<br>Alexa対応音声認識リモコンx1<br>USBケーブルx1<br>HDMI延長ケーブルx1<br>単4電池2本<br>※転送屋不可、海外発送不可<br>転送屋等のご注文と当社が判断した場合、こちらからキャンセル処理させて頂きます。ご理解ご了承の程よろしくお願い致します。<br>配送については最短当日から３営業日以内の発送となります。<br>倉庫保管品につき小さなスレ、ヘコミ等がある場合も御座います。保証印ある場合が御座います。<br>初期不良等の場合はメーカー様にご連絡をお願い致します。※当店では一切保証は受け付けておりません。<br>全ての事をご理解の上、ご購入宜しくお願い致します。<br> 【関連ワード】アマゾンプライム amazonプライムビデオ youtube abema netflix Hulu DAZN dTV wowwow アニメストア ファイヤーTV  ファイアスティックTV　Google クロムキャスト　クロームキャスト　Google Chromecast",
#             "headLine": "FIRE TV スティック　クロームキャスト　Google Chromecast",
#             "url": "https://store.shopping.yahoo.co.jp/premiummarket2/p-001.html",
#             "inStock": true,
#             "code": "premiummarket2_p-001",
#             "condition": "new",
#             "imageId": "premiummarket2_p-001",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/premiummarket2_p-001", "medium": "https://item-shopping.c.yimg.jp/i/g/premiummarket2_p-001" },
#             "review": { "rate": 4.76, "count": 98, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=premiummarket2&page_key=p-001" },
#             "affiliateRate": 1,
#             "price": 3780,
#             "premiumPrice": 3780,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 3780, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 37, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 37, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49552, "name": "その他AV周辺機器", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49518, "name": "AV周辺機器" }
#             ],
#             "brand": { "id": null, "name": "" },
#             "parentBrands": [],
#             "janCode": "0841667185347",
#             "payment": "1 4 16 64 1024 4096 8192 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "premiummarket2",
#                 "name": "プレミアムマーケット",
#                 "url": "https://store.shopping.yahoo.co.jp/premiummarket2/",
#                 "isBestSeller": false,
#                 "isPMallSeller": false,
#                 "review": { "rate": 4.5, "count": 75 },
#                 "imageId": "premiummarket2_1"
#             },
#             "delivery": { "area": "", "deadLine": null, "day": null }
#         },
#         {
#             "index": 2,
#             "name": "HDMIケーブル 2m 1.8m 1m 70cm Ver.2.0b フルハイビジョン HDMI ケーブル 4K 8K 3D 対応 200cm 100cm 2.0m 1.0m HDMI20 AV PC 細線 ハイスピード 送料無料「メ」",
#             "description": "HDMIケーブルです。<br>パソコン(PC)、テレビ(TV)、レコーダー、ゲーム機(Play station / Xbox / Nintendo Switch)などの接続に使用。<br>HIGH-SPEED(ハイスピード)、Ethernet(HEC)、3D、4K(60Hz）8K(30Hz) 対応（8K 30Hz出力はYCbCr 4:2:2で接続できる環境のみ対応）。<br>端子形状はもっとも一般的なタイプA(19ピン)。<br><br>製品仕様<br>UMA-HDMI07/10/18/20<br><br>対応規格<br>HDMI Ver2.0b<br>HIGH-SPEED<br>Ethernet(HEC)<br>3D<br>4K<br>8K 対応(8K出力は30Hz YCbCr 4:2:2で接続できる環境のみ対応)<br><br>端子形状<br>HDMI タイプA(19ピン)-タイプA(19ピン)　金メッキ加工<br><br>ケーブル長<br>70センチ/1.0/1.8/2.0メートル<br><br>主な適合機器<br>HDMI入出力端子を持つ液晶テレビ、ブルーレイレコーダーなど各種レコーダー、AVアンプ、パソコン、ゲーム機<br><br>製品保証<br>保証期間ご購入より1年間<br><br>選べる配送方法<br>・メール便　送料無料。簡易包装でポスト投函。追跡番号なし。あすつく非対象。<br>・宅急便　　送料(別)。佐川急便にて配達。追跡番号あり。あすつく対象。<br><br>関連ワード<br>プレミアム ブルーレイレコーダー DVDプレーヤー HDDレコーダー 接続に PS3 PS4 レグザリンク ビエラリンク 業務用 タブレット 新生活 家電 応援 新品 安い",
#             "headLine": "HDMI ケーブル 2.0規格 ハイスピード ハイスペック 送料無料",
#             "url": "https://store.shopping.yahoo.co.jp/hanwha/uma-hdmi20.html",
#             "inStock": true,
#             "code": "hanwha_uma-hdmi20",
#             "condition": "new",
#             "imageId": "hanwha_uma-hdmi20",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/hanwha_uma-hdmi20", "medium": "https://item-shopping.c.yimg.jp/i/g/hanwha_uma-hdmi20" },
#             "review": { "rate": 4.41, "count": 4585, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=hanwha&page_key=uma-hdmi20" },
#             "affiliateRate": 1,
#             "price": 560,
#             "premiumPrice": 560,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 560, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 5, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 5, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49546, "name": "AV、テレビ用HDMIケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49517, "name": "AVケーブル" }
#             ],
#             "brand": { "id": 16865, "name": "ハンファ" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4543183515061",
#             "payment": "1 4 16 1024 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "hanwha",
#                 "name": "ハンファ・ジャパン",
#                 "url": "https://paypaymall.yahoo.co.jp/store/hanwha/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 10212 },
#                 "imageId": "hanwha_1"
#             },
#             "delivery": { "area": "13", "deadLine": 13, "day": 1 }
#         },
#         {
#             "index": 3,
#             "name": "Fire TV Stick - Alexa対応音声認識リモコン 第3世代",
#             "description": "◆----------------------------------------------------------------------<br>商品状態：新品未開封　「国内正規品」<br><br>付属品 ：外箱記載初期付属品（標準セット）全て新品で揃っています。<br><br>サポート<br>※初期不良含め、故障や品質などのお問い合わせはメーカーより直接対応（交換、修理など）となります。尚、メーカーにより、受付できない場合もございます。当店では返金・交換などの補償はいたしかねますのでご理解の上、ご購入をお願い申し上げます。",
#             "headLine": "大人気 /プレゼント/お祝い/贈り物/0840080588582/",
#             "url": "https://store.shopping.yahoo.co.jp/cosmelifeshop/840080588582.html",
#             "inStock": true,
#             "code": "cosmelifeshop_840080588582",
#             "condition": "new",
#             "imageId": "cosmelifeshop_840080588582",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/cosmelifeshop_840080588582", "medium": "https://item-shopping.c.yimg.jp/i/g/cosmelifeshop_840080588582" },
#             "review": { "rate": 4.67, "count": 15, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=cosmelifeshop&page_key=840080588582" },
#             "affiliateRate": 1,
#             "price": 3896,
#             "premiumPrice": 3896,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 3896, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 38, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 38, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49550, "name": "AV機器用リモコン", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49518, "name": "AV周辺機器" }
#             ],
#             "brand": { "id": null, "name": "" },
#             "parentBrands": [],
#             "janCode": "0840080588582",
#             "payment": "1 16 64 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "cosmelifeshop",
#                 "name": "トクプラストア",
#                 "url": "https://store.shopping.yahoo.co.jp/cosmelifeshop/",
#                 "isBestSeller": false,
#                 "isPMallSeller": false,
#                 "review": { "rate": 4.55, "count": 695 },
#                 "imageId": "cosmelifeshop_1"
#             },
#             "delivery": { "area": "", "deadLine": null, "day": null }
#         },
#         {
#             "index": 4,
#             "name": "テレビ 32インチ 32型 本体 新品 アイリスオーヤマ 液晶テレビ TV 一人暮らし 新生活 ハイビジョンテレビ 32WB10P irsale_tv【OP】",
#             "description": "※ 商品情報や各種ご案内をご確認のうえご注文ください。<br>※ 設置・リサイクルを希望の場合は商品詳細をご確認ください。<br>※ スマホの場合は「さらに表示する」、アプリの場合は「商品情報をもっと見る」を押して詳細をご確認ください。<br><br>●音声出力：光デジタル音声出力、φ3.5mmステレオミニジャック<br>●LAN：LAN端子※データ放送用<br>●アンテナ端子：地上デジタル／BS・110°CSデジタル<br>●チューナー数：地上デジタル、BS・110°CSデジタル<br>●画素数：1366×768<br>●応答速度：6.5ms Gray to gray<br>●視野角：左右約178°/上下約178<br>●スピーカー：2チャンネル、5W＋5W<br>●データ放送：双方向データ放送対応　<br>●電源電圧：AC100V　50/60Hz<br>●消費電力：50W<br>●省エネ達成率：133％<br>●電源ケーブル長さ：約1.5m<br>●商品サイズ(cm)：幅約73.2×高さ約47.7×奥行約18<br>●付属品：リモコン、リモコン用単4乾電池個、mini B-CASカード枚、スタンドベースセット、スタンドベース固定ネジ、取扱説明書、保証書、AV変換ケーブル<br><br>▼追加オプションを選択して頂いた場合<br>Google Chromecast<br>●JAN：0842776106230<br>●商品サイズ(cm)：直径約5.19×幅約1.38<br>●本体質量：約40g<br>●電源ケーブル：約1.52m",
#             "headLine": "32インチ テレビ 32型 本体 新品 液晶テレビ アイリスオーヤマ",
#             "url": "https://store.shopping.yahoo.co.jp/petkan/509552.html",
#             "inStock": true,
#             "code": "petkan_509552",
#             "condition": "new",
#             "imageId": "petkan_509552",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/petkan_509552", "medium": "https://item-shopping.c.yimg.jp/i/g/petkan_509552" },
#             "review": { "rate": 4.38, "count": 853, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=petkan&page_key=509552" },
#             "affiliateRate": 1,
#             "price": 22800,
#             "premiumPrice": 22800,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 22800, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 228, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 228, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49520, "name": "液晶テレビ、薄型テレビ", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49514, "name": "テレビ" }
#             ],
#             "brand": { "id": 113, "name": "IRIS OHYAMA" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4967576439398",
#             "payment": "1 2 4 16 256 512 1024 4096 8192",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "petkan",
#                 "name": "megastore PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/petkan/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.43, "count": 70058 },
#                 "imageId": "petkan_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 5,
#             "name": "東芝 ハイビジョンLED液晶テレビ 32型 地上・BS・110度CSデジタル REGZA 32V34",
#             "description": "",
#             "headLine": "",
#             "url": "https://store.shopping.yahoo.co.jp/gbft-online/p9-sedo-lwwh.html",
#             "inStock": true,
#             "code": "gbft-online_p9-sedo-lwwh",
#             "condition": "new",
#             "imageId": "gbft-online_p9-sedo-lwwh",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/gbft-online_p9-sedo-lwwh", "medium": "https://item-shopping.c.yimg.jp/i/g/gbft-online_p9-sedo-lwwh" },
#             "review": { "rate": 4.75, "count": 48, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=gbft-online&page_key=p9-sedo-lwwh" },
#             "affiliateRate": 1,
#             "price": 34347,
#             "premiumPrice": 34347,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 34347, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 343, "times": 1, "bonusAmount": 343, "bonusTimes": 1, "premiumAmount": 343, "premiumTimes": 1, "premiumBonusAmount": 343, "premiumBonusTimes": 1 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49520, "name": "液晶テレビ、薄型テレビ", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49514, "name": "テレビ" }
#             ],
#             "brand": { "id": 4708, "name": "REGZA" },
#             "parentBrands": [
#                 { "id": 1, "name": "ブランド" },
#                 { "id": 2352, "name": "東芝" }
#             ],
#             "janCode": "4580652110471",
#             "payment": "1 4 16 64 1024 4096 8192 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "gbft-online",
#                 "name": "GBFT Online Yahoo!ショッピング店",
#                 "url": "https://store.shopping.yahoo.co.jp/gbft-online/",
#                 "isBestSeller": false,
#                 "isPMallSeller": false,
#                 "review": { "rate": 4.7, "count": 1946 },
#                 "imageId": "gbft-online_1"
#             },
#             "delivery": { "area": "13", "deadLine": 12, "day": 1 }
#         },
#         {
#             "index": 6,
#             "name": "Google Chromecast GA00439-JP チャコール 正規品 第三世代 2K対応",
#             "description": "[サイズ]<br>直径:51.9 mm<br>幅:13.8mm<br>電源ケーブル:1.52 m<br>[重量]<br>40 g<br>[解像度]<br>最大 1080p、60 fps<br>[無線]<br>すべてのワイヤレス ネットワークに対応:Wi-Fi 802.11ac(2.4 GHz / 5 GHz)<br>[ポートとコネクタ]<br>HDMI 端子(テレビに直接つなぎます)<br>Micro-USB(電源とデータ用です)",
#             "headLine": "最安値へ向けて挑戦しています！",
#             "url": "https://store.shopping.yahoo.co.jp/ginganet/ga00439-jp.html",
#             "inStock": true,
#             "code": "ginganet_ga00439-jp",
#             "condition": "new",
#             "imageId": "ginganet_ga00439-jp",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/ginganet_ga00439-jp", "medium": "https://item-shopping.c.yimg.jp/i/g/ginganet_ga00439-jp" },
#             "review": { "rate": 4.7, "count": 121, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=ginganet&page_key=ga00439-jp" },
#             "affiliateRate": 1,
#             "price": 3558,
#             "premiumPrice": 3558,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 3558, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 35, "times": 1, "bonusAmount": 70, "bonusTimes": 2, "premiumAmount": 35, "premiumTimes": 1, "premiumBonusAmount": 70, "premiumBonusTimes": 2 },
#             "shipping": { "code": 3, "name": "条件付き送料無料" },
#             "genreCategory": { "id": 49552, "name": "その他AV周辺機器", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49518, "name": "AV周辺機器" }
#             ],
#             "brand": { "id": 17565, "name": "クロームキャスト" },
#             "parentBrands": [
#                 { "id": 1, "name": "ブランド" },
#                 { "id": 17584, "name": "Google" }
#             ],
#             "janCode": "0842776106230",
#             "payment": "1 16 64 256 512 1024 4096 8192 16384",
#             "releaseDate": null,
#             "seller": { "sellerId": "ginganet", "name": "銀河ネット", "url": "https://store.shopping.yahoo.co.jp/ginganet/", "isBestSeller": false, "isPMallSeller": false, "review": { "rate": 4.76, "count": 83 }, "imageId": "ginganet_1" },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 7,
#             "name": "アンテナケーブル 同軸ケーブル 2m 4k対応 8K対応 テレビ BS CS 地デジ 衛星放送 アンテナ ケーブル コード TV 2.0m 200cm 種類 延長 送料無料 「メ」",
#             "description": "アンテナケーブルです。<br>プラグはネジ式F型ストレート - プッシュ式L型<br>減衰の少ない金メッキ加工。<br>4K/8K放送(3224MHz）対応のS-4C-FB(S4C-FB)規格ケーブル。<br><br>製品仕様<br>製品型番：UMA-ATC20FL<br>a 商品概要：CS/BS/地上デジタル(地デジ)対応 アンテナケーブル 75Ω OFC S4C-FB<br>ケーブル長：2.0m(200cm)<br>対応周波数：5〜2610MHz<br>製品保証：保証期間ご購入より1年間<br><br>選べる配送方法<br>・メール便　送料無料。簡易包装でポスト投函。追跡番号なし。あすつく非対象。<br>・宅急便　送料(別)。佐川急便にて配達。追跡番号あり。あすつく対象。",
#             "headLine": "TVケーブル アンテナ アンテナ線 ポイント消化 低減衰ケーブル",
#             "url": "https://store.shopping.yahoo.co.jp/hanwha/uma-atc20fl.html",
#             "inStock": true,
#             "code": "hanwha_uma-atc20fl",
#             "condition": "new",
#             "imageId": "hanwha_uma-atc20fl",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/hanwha_uma-atc20fl", "medium": "https://item-shopping.c.yimg.jp/i/g/hanwha_uma-atc20fl" },
#             "review": { "rate": 4.43, "count": 42, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=hanwha&page_key=uma-atc20fl" },
#             "affiliateRate": 1,
#             "price": 490,
#             "premiumPrice": 490,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 490, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 4, "times": 1, "bonusAmount": 4, "bonusTimes": 1, "premiumAmount": 4, "premiumTimes": 1, "premiumBonusAmount": 16, "premiumBonusTimes": 4 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49541, "name": "アンテナケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49516, "name": "テレビチューナー、アンテナ" }
#             ],
#             "brand": { "id": 16865, "name": "ハンファ" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4543183527057",
#             "payment": "1 4 16 1024 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "hanwha",
#                 "name": "ハンファ・ジャパン",
#                 "url": "https://paypaymall.yahoo.co.jp/store/hanwha/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 10212 },
#                 "imageId": "hanwha_1"
#             },
#             "delivery": { "area": "13", "deadLine": 13, "day": 1 }
#         },
#         {
#             "index": 8,
#             "name": "4K8K放送(3224MHz)対応 2C出力ケーブル付 分波器 (BS/CS・地デジ・CATV対応) (F型-F型) ケーブル長20cm ニッケルメッキ ホワイトまたはブラック",
#             "description": "4K8K放送に対応したアンテナ分波器です。とりまわしやすく、薄型テレビに最適な極細2CFBケーブル採用。トリプルシールド（3重シールド）構造でノイズが少ない。お部屋の壁のテレビコンセント（アンテナ端子）からテレビケーブルを経由してBS・110度CSデジタル電波と地上デジタル（UHF）電波に分波するBS/UV分波器(セパレータ)です。CATVからの地デジ信号とBS/CS信号の分波もできます。地デジアンテナとBS・CSアンテナの混合した電波を、テレビやレコーダーに接続する際に地デジとBS・CSの電波に分けるのにご使用いただけます。 <br>コンパクトなボディと、長さ20cmのケーブルにより配線しやすくテレビ背面がすっきりします。また、2CFBの3重シールド構造でノイズが少なく、4K8K放送の地上デジタル・BSデジタル・110度CSデジタルに必須の高シールドタイプ。また、本体内部は金属ケースによりノイズを防ぎます。<br>4K ・8K 放送対応分波器。使用帯域:10MHz〜3224MHz<br>ケーブル長:20cm、入力端子:F型ジャック、出力端子:F型接栓プラグ、プラグ部分：ニッケルメッキ <br>BSとCSの分波及び混合には使えません。屋内専用商品です。分配器ではありません。簡易パッケージになります。",
#             "headLine": "4K8K対応の分波器！電波をテレビ裏で2つに分波します",
#             "url": "https://store.shopping.yahoo.co.jp/f-fact/ff-4877.html",
#             "inStock": true,
#             "code": "f-fact_ff-4877",
#             "condition": "new",
#             "imageId": "f-fact_ff-4877",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/f-fact_ff-4877", "medium": "https://item-shopping.c.yimg.jp/i/g/f-fact_ff-4877" },
#             "review": { "rate": 4.55, "count": 798, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=f-fact&page_key=ff-4877" },
#             "affiliateRate": 1,
#             "price": 665,
#             "premiumPrice": 665,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 665, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 6, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 6, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49543, "name": "アンテナ分波器", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49516, "name": "テレビチューナー、アンテナ" }
#             ],
#             "brand": { "id": 36970, "name": "富士パーツ商会" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "",
#             "payment": "1 4096",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "f-fact",
#                 "name": "F-Factory ヤフー店",
#                 "url": "https://store.shopping.yahoo.co.jp/f-fact/",
#                 "isBestSeller": false,
#                 "isPMallSeller": false,
#                 "review": { "rate": 4.63, "count": 9284 },
#                 "imageId": "f-fact_1"
#             },
#             "delivery": { "area": "13", "deadLine": 14, "day": 1 }
#         },
#         {
#             "index": 9,
#             "name": "HIDISC 16倍速対応DVD-R 50枚パック 4.7GB ホワイトプリンタブル ハイディスク 詰め替え用 HDDR12JCP50SB2 返品種別A",
#             "description": "在庫状況：お取り寄せ/◆一度だけ録画が可能なDVD-Rディスク◆スピンドルケースに簡単手軽に詰め替えが可能な簡易包装◆インクジェットプリンタ対応ワイドプリンタブル/[HDDR12JCP50SB2]",
#             "headLine": "",
#             "url": "https://store.shopping.yahoo.co.jp/joshin/4984279130070-31-22932.html",
#             "inStock": true,
#             "code": "joshin_4984279130070-31-22932",
#             "condition": "new",
#             "imageId": "joshin_4984279130070-31-22932",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/joshin_4984279130070-31-22932", "medium": "https://item-shopping.c.yimg.jp/i/g/joshin_4984279130070-31-22932" },
#             "review": { "rate": 4.39, "count": 176, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=joshin&page_key=4984279130070-31-22932" },
#             "affiliateRate": 1,
#             "price": 980,
#             "premiumPrice": 980,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 980, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 9, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 9, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 1, "name": "設定なし" },
#             "genreCategory": { "id": 49534, "name": "録画用メディア その他", "depth": 5 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49515, "name": "ブルーレイ、DVDレコーダー" },
#                 { "depth": 4, "id": 49526, "name": "録画用メディア" }
#             ],
#             "brand": { "id": 17449, "name": "HIDISC" },
#             "parentBrands": [
#                 { "id": 1, "name": "ブランド" },
#                 { "id": 18019, "name": "磁気研究所" }
#             ],
#             "janCode": "4984279130070",
#             "payment": "1 16 4096",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "joshin",
#                 "name": "Joshin web",
#                 "url": "https://paypaymall.yahoo.co.jp/store/joshin/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 383479 },
#                 "imageId": "joshin_1"
#             },
#             "delivery": { "area": "", "deadLine": null, "day": null }
#         },
#         {
#             "index": 10,
#             "name": "HDMIケーブル 3m Ver.2.0b フルハイビジョン HDMI ケーブル 4K 8K 3D 対応 3.0m 300cm HDMI30 AV PC 細線 ハイスピード 送料無料 「メ」",
#             "description": "HDMIケーブルです。<br>パソコン(PC)、テレビ(TV)、レコーダー、ゲーム機(Play station / Xbox / Nintendo Switch)などの接続に使用します。<br>HIGH-SPEED(ハイスピード)、Ethernet(HEC)、3D、4K(60Hz) 8K(30Hz)対応（8K 30Hz出力はYCbCr 4:2:2で接続できる環境のみ対応）。<br>端子形状はもっとも一般的なタイプA(19ピン)、金メッキ加工。<br><br>製品仕様<br>型番：UMA-HDMI30<br>対応規格：HDMI Ver2.0b<br>HIGH-SPEED / Ethernet(HEC) / 3D / 4K / 8K 対応(8K出力は30Hz YCbCr 4:2:2で接続できる環境のみ対応)<br>端子形状：HDMI タイプA(19ピン)-タイプA(19ピン)　金メッキ加工<br>ケーブル長：3.0メートル<br>主な適合機器：HDMI入出力端子を持つ液晶テレビ、ブルーレイレコーダーなど各種レコーダー、AVアンプ、パソコン、ゲーム機など。<br>製品保証：保証期間ご購入より1年間<br><br>選べる配送方法<br>・メール便　送料無料。簡易包装でポスト投函。追跡番号なし。あすつく非対象。<br>・宅急便　　送料(別)。佐川急便にて配達。追跡番号あり。あすつく対象。<br><br>関連ワード<br>プレミアム ブルーレイレコーダー DVDプレーヤー HDDレコーダー 接続 PS3 PS4 レグザリンク ビエラリンク 業務用 パソコン タブレット 延長コードより最適な長さ",
#             "headLine": "HDMI ケーブル 2.0規格 ハイスピード ハイスペック 送料無料",
#             "url": "https://store.shopping.yahoo.co.jp/hanwha/uma-hdmi30.html",
#             "inStock": true,
#             "code": "hanwha_uma-hdmi30",
#             "condition": "new",
#             "imageId": "hanwha_uma-hdmi30",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/hanwha_uma-hdmi30", "medium": "https://item-shopping.c.yimg.jp/i/g/hanwha_uma-hdmi30" },
#             "review": { "rate": 4.45, "count": 2133, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=hanwha&page_key=uma-hdmi30" },
#             "affiliateRate": 1,
#             "price": 660,
#             "premiumPrice": 660,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 660, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 6, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 6, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49546, "name": "AV、テレビ用HDMIケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49517, "name": "AVケーブル" }
#             ],
#             "brand": { "id": 16865, "name": "ハンファ" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4543183515078",
#             "payment": "1 4 16 1024 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "hanwha",
#                 "name": "ハンファ・ジャパン",
#                 "url": "https://paypaymall.yahoo.co.jp/store/hanwha/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 10212 },
#                 "imageId": "hanwha_1"
#             },
#             "delivery": { "area": "13", "deadLine": 13, "day": 1 }
#         },
#         {
#             "index": 11,
#             "name": "テレビ 24インチ 24型 本体 新品 アイリス 液晶テレビ アイリスオーヤマ TV 一人暮らし ハイビジョンテレビ 24V ブラック 24WB10【OP】",
#             "description": "※ 商品情報や各種ご案内をご確認のうえご注文ください。<br>※ 設置・リサイクルを希望の場合は商品詳細をご確認ください。<br>※ スマホの場合は「さらに表示する」、アプリの場合は「商品情報をもっと見る」を押して詳細をご確認ください。<br><br>●品名：ハイビジョン液晶テレビ<br>●画面サイズ：24V型(幅約52.1×高さ約29.3×対角59.9cm)<br>●商品サイズ（cm）：幅約54.9×奥行約13.1×高さ約36.7<br>●商品質量：約2.6kg<br>●チューナー<br>受信チャンネル<br>　地上デジタル：UHF（13〜62ch）CATVパススルー対応<br>　BSデジタル：BS000〜BS999<br>　110度CSデジタル：CS000〜CS999<br>チューナー数：地上デジタル×2、BS・110度CSデジタル×2<br>●データ放送：双方向データ放送（BML）対応<br>：電子番組表（EPG）対応：7チャンネル6時間分表示／8日分受信<br>●録画機能(ハードディスク(別売り)がないとできません。)<br>●付属品：リモコン、リモコン用単4乾電池×2、miniB-CASカード、スタンド×2、スタンド固定用ねじ×4、AV入力アダプター<br><br>▼追加オプションを選択して頂いた場合<br>Google Chromecast<br>●JAN：0842776106230<br>●商品サイズ(cm)：直径約5.19×幅約1.38<br>●本体質量：約40g<br>●電源ケーブル：約1.52m",
#             "headLine": "24型 テレビ 液晶テレビ アイリスオーヤマ",
#             "url": "https://store.shopping.yahoo.co.jp/petkan/573803.html",
#             "inStock": true,
#             "code": "petkan_573803",
#             "condition": "new",
#             "imageId": "petkan_573803",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/petkan_573803", "medium": "https://item-shopping.c.yimg.jp/i/g/petkan_573803" },
#             "review": { "rate": 4.38, "count": 352, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=petkan&page_key=573803" },
#             "affiliateRate": 1,
#             "price": 19800,
#             "premiumPrice": 19800,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 19800, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 198, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 198, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49520, "name": "液晶テレビ、薄型テレビ", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49514, "name": "テレビ" }
#             ],
#             "brand": { "id": 113, "name": "IRIS OHYAMA" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4967576469081",
#             "payment": "1 2 4 16 256 512 1024 4096 8192",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "petkan",
#                 "name": "megastore PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/petkan/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.43, "count": 70085 },
#                 "imageId": "petkan_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 12,
#             "name": "Verbatim　BD-R（1回録画用）　1-6倍速　50枚　VBR130RP50V4　三菱ケミカルメディア",
#             "description": "※ご注文の確定タイミングにより、在庫が確保できない場合がございます。<br>「ご注文を確定」する際に再度ご確認ください。<br>BD-R（Video） 1回録画用 130分 1-6倍速 50枚スピンドルケース50P インクジェットプリンタ対応（ホワイト） ワイド印刷エリア対応<br>BD-R（Video） 1回録画用 130分 1-6倍速 50枚スピンドルケース50P インクジェットプリンタ対応（ホワイト） ワイド印刷エリア対応。独自開発のカバー層を採用、ハードコート層と共に、記録層をダメージから強力に守ります。キズ、ホコリ、指紋に強く、記録層をダメージから守ります。さらに指紋等の汚れが付きにくく、簡単に拭き取ることができます。<br>家電・PC・周辺機器 ＞ 記録メディア・メモリーカード ＞ ブルーレイディスク ＞ BD-R（録画用）",
#             "headLine": "BD-R（録画用）",
#             "url": "https://store.shopping.yahoo.co.jp/y-lohaco/3429345.html",
#             "inStock": true,
#             "code": "y-lohaco_3429345",
#             "condition": "new",
#             "imageId": "y-lohaco_3429345",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/y-lohaco_3429345", "medium": "https://item-shopping.c.yimg.jp/i/g/y-lohaco_3429345" },
#             "review": { "rate": 4.57, "count": 264, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=y-lohaco&page_key=3429345" },
#             "affiliateRate": 1,
#             "price": 2315,
#             "premiumPrice": 2315,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 2315, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 23, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 23, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 3, "name": "条件付き送料無料" },
#             "genreCategory": { "id": 49377, "name": "記録用ブルーレイディスクメディア（BD）", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2502, "name": "スマホ、タブレット、パソコン" },
#                 { "depth": 2, "id": 113, "name": "PCサプライ、アクセサリー" },
#                 { "depth": 3, "id": 49360, "name": "データ用メディア" }
#             ],
#             "brand": { "id": 19551, "name": "三菱ケミカルメディア" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4991348066994",
#             "payment": "1 16 4096",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "y-lohaco",
#                 "name": "LOHACO PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/y-lohaco/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.66, "count": 99137 },
#                 "imageId": "y-lohaco_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 13,
#             "name": "HDMIケーブル 5m Ver.2.0b フルハイビジョン HDMI ケーブル 4K 8K 3D 対応 5.0m 500cm HDMI50 AV PC 細線 ハイスピード 送料無料 「メ」",
#             "description": "HDMIケーブルです。<br>パソコン(PC)、テレビ(TV)、レコーダー、ゲーム機(Play station / Xbox / Nintendo Switch)などの接続に使用します。<br>HIGH-SPEED(ハイスピード)、Ethernet(HEC)、3D、4K(60Hz) 8K(30Hz) 対応（8K 30Hz出力はYCbCr 4:2:2で接続できる環境のみ対応）。<br>端子形状はもっとも一般的なタイプA(19ピン)、金メッキ加工。<br><br>製品仕様<br>型番：UMA-HDMI50<br>対応規格：HDMI Ver2.0b<br>HIGH-SPEED / Ethernet(HEC) / 3D / 4K / 8K 対応(8K出力は30Hz YCbCr 4:2:2で接続できる環境のみ対応)<br>端子形状：HDMI タイプA(19ピン)-タイプA(19ピン)　金メッキ加工<br>ケーブル長：5.0メートル<br>主な適合機器：HDMI入出力端子を持つ液晶テレビ、ブルーレイレコーダーなど各種レコーダー、AVアンプ、パソコン、ゲーム機など。<br>製品保証：保証期間ご購入より1年間<br><br>選べる配送方法<br>・メール便　送料無料。簡易包装でポスト投函。追跡番号なし。あすつく非対象。<br>・宅急便　　送料(別)。佐川急便にて配達。追跡番号あり。あすつく対象。<br><br>関連ワード<br>プレミアム ブルーレイレコーダー DVDプレーヤー HDDレコーダー 接続 PS3 PS4 レグザリンク ビエラリンク 業務用 パソコン タブレット 延長コードより最適な長さ",
#             "headLine": "HDMI ケーブル 2.0規格 ハイスピード ハイスペック 送料無料",
#             "url": "https://store.shopping.yahoo.co.jp/hanwha/uma-hdmi50.html",
#             "inStock": true,
#             "code": "hanwha_uma-hdmi50",
#             "condition": "new",
#             "imageId": "hanwha_uma-hdmi50",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/hanwha_uma-hdmi50", "medium": "https://item-shopping.c.yimg.jp/i/g/hanwha_uma-hdmi50" },
#             "review": { "rate": 4.45, "count": 1890, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=hanwha&page_key=uma-hdmi50" },
#             "affiliateRate": 1,
#             "price": 788,
#             "premiumPrice": 788,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 788, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 7, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 7, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49546, "name": "AV、テレビ用HDMIケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49517, "name": "AVケーブル" }
#             ],
#             "brand": { "id": 16865, "name": "ハンファ" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4543183515092",
#             "payment": "1 4 16 1024 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "hanwha",
#                 "name": "ハンファ・ジャパン",
#                 "url": "https://paypaymall.yahoo.co.jp/store/hanwha/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 10212 },
#                 "imageId": "hanwha_1"
#             },
#             "delivery": { "area": "13", "deadLine": 13, "day": 1 }
#         },
#         {
#             "index": 14,
#             "name": "テレビ 50インチ 4K 50型 本体 新品 アイリス 液晶テレビ アイリスオーヤマ 4Kテレビ 4K対応 4K対応液晶テレビ ブラック 50UB10P【OP】",
#             "description": "※ 商品情報や各種ご案内をご確認のうえご注文ください。<br>※ 設置・リサイクルを希望の場合は商品詳細をご確認ください。<br><br>●チューナー数：地上デジタル×2、BS・110°CSデジタル×2　※1<br>●画素数(水平×垂直)：3840×2160<br>●視野角(最小値)：左右約178°(TYP)／上下約178°(TYP)<br>●スピーカー：2チャンネル、8W＋8W<br>●年間消費電力量：182kWh/年　※2<br>●電源ケーブル長さ：約1.5m<br>●商品サイズ(cm)：幅約112.3×高さ約70.9×奥行約24.7<br>●付属品：付属品：スタンドベース×2個、スタンドベース固定ネジ×4個、電源コード、AV入力アダプター、リモコン、リモコン用単4乾電池(テスト用)×2個、mini B-CASカード×1枚、取扱説明書、保証書<br><br>※2 省エネ法に基づき、1日あたり4.5Hの動作時間/19.5Hの待機時間(電子番組表取得時間を含む)で算出した、1年間に使用する電力量です。<br><br>▼追加オプションを選択して頂いた場合<br>Google Chromecast<br>●JAN：0842776106230<br>●商品サイズ(cm)：直径約5.19×幅約1.38<br>●本体質量：約40g<br>●電源ケーブル：約1.52m<br><br>サウンドスピーカー<br>●商品サイズ(cm)<br>幅約80×奥行約8.4×高さ約6.6",
#             "headLine": "50インチ 4Kテレビ 50型",
#             "url": "https://store.shopping.yahoo.co.jp/petkan/513848.html",
#             "inStock": true,
#             "code": "petkan_513848",
#             "condition": "new",
#             "imageId": "petkan_513848",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/petkan_513848", "medium": "https://item-shopping.c.yimg.jp/i/g/petkan_513848" },
#             "review": { "rate": 4.29, "count": 402, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=petkan&page_key=513848" },
#             "affiliateRate": 1,
#             "price": 48800,
#             "premiumPrice": 48800,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": "sale",
#             "premiumDiscountRate": 2,
#             "priceLabel": { "taxable": true, "defaultPrice": 49800, "discountedPrice": 48800, "fixedPrice": null, "premiumPrice": null, "periodStart": 1646452800, "periodEnd": 1646967600 },
#             "point": { "amount": 488, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 488, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49520, "name": "液晶テレビ、薄型テレビ", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49514, "name": "テレビ" }
#             ],
#             "brand": { "id": 113, "name": "IRIS OHYAMA" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4967576439428",
#             "payment": "1 2 4 16 256 512 1024 4096 8192",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "petkan",
#                 "name": "megastore PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/petkan/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.43, "count": 70186 },
#                 "imageId": "petkan_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 15,
#             "name": "アンテナケーブル 同軸ケーブル 3m 4k対応 8K対応 テレビ BS CS 地デジ 衛星放送 アンテナ ケーブル コード TV 3.0m 300cm 種類 延長 送料無料 「メ」",
#             "description": "アンテナケーブルです。<br>プラグはネジ式F型ストレート - プッシュ式L型<br>減衰の少ない金メッキ加工。<br>4K/8K放送(3224MHz）対応のS-4C-FB(S4C-FB)規格ケーブル。<br><br>製品仕様<br>製品型番：UMA-ATC30FL<br>a 商品概要：CS/BS/地上デジタル(地デジ)対応 アンテナケーブル 75Ω OFC S4C-FB<br>ケーブル長：3.0m(300cm)<br>対応周波数：5〜2610MHz<br>製品保証：保証期間ご購入より1年間<br><br>選べる配送方法<br>・メール便　送料無料。簡易包装でポスト投函。追跡番号なし。あすつく非対象。<br>・宅急便　送料(別)。佐川急便にて配達。追跡番号あり。あすつく対象。",
#             "headLine": "TVケーブル アンテナ アンテナ線 ポイント消化 低減衰ケーブル",
#             "url": "https://store.shopping.yahoo.co.jp/hanwha/uma-atc30fl.html",
#             "inStock": true,
#             "code": "hanwha_uma-atc30fl",
#             "condition": "new",
#             "imageId": "hanwha_uma-atc30fl",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/hanwha_uma-atc30fl", "medium": "https://item-shopping.c.yimg.jp/i/g/hanwha_uma-atc30fl" },
#             "review": { "rate": 4.54, "count": 35, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=hanwha&page_key=uma-atc30fl" },
#             "affiliateRate": 1,
#             "price": 590,
#             "premiumPrice": 590,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 590, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 5, "times": 1, "bonusAmount": 5, "bonusTimes": 1, "premiumAmount": 5, "premiumTimes": 1, "premiumBonusAmount": 20, "premiumBonusTimes": 4 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49541, "name": "アンテナケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49516, "name": "テレビチューナー、アンテナ" }
#             ],
#             "brand": { "id": 16865, "name": "ハンファ" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4543183527064",
#             "payment": "1 4 16 1024 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "hanwha",
#                 "name": "ハンファ・ジャパン",
#                 "url": "https://paypaymall.yahoo.co.jp/store/hanwha/top/",
#                 "isBestSeller": false,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 10212 },
#                 "imageId": "hanwha_1"
#             },
#             "delivery": { "area": "13", "deadLine": 13, "day": 1 }
#         },
#         {
#             "index": 16,
#             "name": "ソニー　SONY　ブルーレイレコーダー 1TB 2番組同時録画　BDZ-ZW1800",
#             "description": "",
#             "headLine": "",
#             "url": "https://store.shopping.yahoo.co.jp/y-kojima/4548736122185.html",
#             "inStock": true,
#             "code": "y-kojima_4548736122185",
#             "condition": "new",
#             "imageId": "y-kojima_4548736122185",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/y-kojima_4548736122185", "medium": "https://item-shopping.c.yimg.jp/i/g/y-kojima_4548736122185" },
#             "review": { "rate": 4.79, "count": 14, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=y-kojima&page_key=4548736122185" },
#             "affiliateRate": 1,
#             "price": 41947,
#             "premiumPrice": 41947,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 41947, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 419, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 419, "premiumTimes": 1, "premiumBonusAmount": 419, "premiumBonusTimes": 1 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49524, "name": "ポータブルブルーレイ、DVDプレーヤー", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49515, "name": "ブルーレイ、DVDレコーダー" }
#             ],
#             "brand": { "id": 1091, "name": "ソニー" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4548736122185",
#             "payment": "1 4 16 4096 16384",
#             "releaseDate": 1619794800,
#             "seller": {
#                 "sellerId": "y-kojima",
#                 "name": "コジマPayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/y-kojima/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.59, "count": 182059 },
#                 "imageId": "y-kojima_1"
#             },
#             "delivery": { "area": "13", "deadLine": 16, "day": 1 }
#         },
#         {
#             "index": 17,
#             "name": "ソニー 1TB HDD/ 2チューナー搭載 ブルーレイレコーダー SONY BRAVIA(ブラビア) Zシリーズ BDZ-ZW1800 返品種別A",
#             "description": "在庫状況：在庫あり/※配達時に設置をご依頼の場合、別途有料にて承ります。(Aエリア内)　設置を依頼される場合は、ご注文時にお申し付け下さい。※HDMIケーブルは別売です。本機はアナログ出力がありません。HDMI端子のないテレビでは、ご利用できません。※(新4K衛星放送)およびBS/110度CSデジタル放送の受信には視聴する放送に対応した衛星アンテナおよび受信設備が必要です。※Ultra HD Blu-ray 視聴の際は、対応する4K対応テレビと(プレミアムHDMIケーブル)で本機を接続することによりUHD画質を楽しむことができます。※ご注文に関しましては、お1人様1台でお願いします。複数ご購入はご遠慮ください。※同一住所で名前を変えてのご注文など、同一と思われるお客様より複数のご注文をいただいた場合、　ご注文をキャンセルさせていただくこともございますのでご了承ください。◆録っても賢いソニーのブルーレイ◆充実の録画機能搭載モデル/[BDZZW1800]",
#             "headLine": "",
#             "url": "https://store.shopping.yahoo.co.jp/joshin/4548736122185-31-16315.html",
#             "inStock": true,
#             "code": "joshin_4548736122185-31-16315",
#             "condition": "new",
#             "imageId": "joshin_4548736122185-31-16315",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/joshin_4548736122185-31-16315", "medium": "https://item-shopping.c.yimg.jp/i/g/joshin_4548736122185-31-16315" },
#             "review": { "rate": 4.64, "count": 14, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=joshin&page_key=4548736122185-31-16315" },
#             "affiliateRate": 1,
#             "price": 41947,
#             "premiumPrice": 41947,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 41947, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 419, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 419, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49522, "name": "ブルーレイ、DVDレコーダー本体", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49515, "name": "ブルーレイ、DVDレコーダー" }
#             ],
#             "brand": { "id": 1091, "name": "ソニー" },
#             "parentBrands": [{ "id": 1, "name": "ブランド" }],
#             "janCode": "4548736122185",
#             "payment": "1 16 4096",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "joshin",
#                 "name": "Joshin web",
#                 "url": "https://paypaymall.yahoo.co.jp/store/joshin/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.51, "count": 383458 },
#                 "imageId": "joshin_1"
#             },
#             "delivery": { "area": "", "deadLine": null, "day": null }
#         },
#         {
#             "index": 18,
#             "name": "HDMIケーブル 2m HDMIver1.4 金メッキ端子 High Speed HDMI Cable ブラック ハイスピード 4K 3D イーサネット対応 液晶テレビ ブルーレイレコーダー UL.YN",
#             "description": "HDMIケーブル 2m HDMIver1.4 金メッキ端子 High Speed HDMI Cable ブラック ハイスピード 4K 3D イーサネット対応 液晶テレビ ブルーレイレコーダー DVDプレーヤー ゲーム機との接続に ☆UL-CAVS009★ |1402ULZM^ UL.YN",
#             "headLine": "この商品の配送方法「メール便」",
#             "url": "https://store.shopping.yahoo.co.jp/musasinojapan/4589684719898.html",
#             "inStock": true,
#             "code": "musasinojapan_4589684719898",
#             "condition": "new",
#             "imageId": "musasinojapan_4589684719898",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/musasinojapan_4589684719898", "medium": "https://item-shopping.c.yimg.jp/i/g/musasinojapan_4589684719898" },
#             "review": { "rate": 4.5, "count": 452, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=musasinojapan&page_key=4589684719898" },
#             "affiliateRate": 1,
#             "price": 284,
#             "premiumPrice": 284,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 284, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 2, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 2, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49546, "name": "AV、テレビ用HDMIケーブル", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49517, "name": "AVケーブル" }
#             ],
#             "brand": { "id": 29450, "name": "2M" },
#             "parentBrands": [
#                 { "id": 1, "name": "ブランド" },
#                 { "id": 4529, "name": "ortofon" }
#             ],
#             "janCode": "4589684719898",
#             "payment": "1 2 8 16 4096 8192 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "musasinojapan",
#                 "name": "むさしのジャパン",
#                 "url": "https://store.shopping.yahoo.co.jp/musasinojapan/",
#                 "isBestSeller": false,
#                 "isPMallSeller": false,
#                 "review": { "rate": 4.63, "count": 1874 },
#                 "imageId": "musasinojapan_1"
#             },
#             "delivery": { "area": "", "deadLine": null, "day": null }
#         },
#         {
#             "index": 19,
#             "name": "Amazon B08MRXN5GS Fire TV Stick 4K Max - Alexa対応音声認識リモコン(第3世代)付属 ストリーミングメディアプレーヤー   ブラック",
#             "description": "Amazon　B08MRXN5GS　Fire　TV　Stick　4K　Max　-　Alexa対応音声認識リモコン(第3世代)付属　ストリーミングメディアプレーヤー　　　ブラック 111",
#             "headLine": "",
#             "url": "https://store.shopping.yahoo.co.jp/yamada-denki/4733550016.html",
#             "inStock": true,
#             "code": "yamada-denki_4733550016",
#             "condition": "new",
#             "imageId": "yamada-denki_4733550016",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/yamada-denki_4733550016", "medium": "https://item-shopping.c.yimg.jp/i/g/yamada-denki_4733550016" },
#             "review": { "rate": 4.71, "count": 35, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=yamada-denki&page_key=4733550016" },
#             "affiliateRate": 1,
#             "price": 6979,
#             "premiumPrice": 6979,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 6979, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": null, "periodEnd": null },
#             "point": { "amount": 69, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 69, "premiumTimes": 1, "premiumBonusAmount": 138, "premiumBonusTimes": 2 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49552, "name": "その他AV周辺機器", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49518, "name": "AV周辺機器" }
#             ],
#             "brand": { "id": null, "name": "" },
#             "parentBrands": [],
#             "janCode": "0840080526935",
#             "payment": "1 16 4096 16384",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "yamada-denki",
#                 "name": "ヤマダデンキ PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/yamada-denki/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.28, "count": 52129 },
#                 "imageId": "yamada-denki_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         },
#         {
#             "index": 20,
#             "name": "テレビ 32型 本体 新品 アイリス 液晶テレビ 32インチ ハイビジョンテレビ TV アイリスオーヤマ 一人暮らし LUCA ホワイト ブラック【OP】",
#             "description": "※ 商品情報や各種ご案内をご確認のうえご注文ください。<br>※ 設置・リサイクルを希望の場合は商品詳細をご確認ください。<br>※ スマホの場合は「さらに表示する」、アプリの場合は「商品情報をもっと見る」を押して詳細をご確認ください。<br><br>●画素数：1366×768<br>●チューナー数：地上デジタル×2、BC・110度CSデジタル×2<br>●地上波デジタル：UHF(13〜62ch)CATVパススルー(VHF、UHF)対応共有<br>●BSデジタル：BS000〜BS999<br>●110°CS デジタル：CS000〜CS999<br>●ヘッドホン出力：Φ3.5mmステレオミニジャック、適合インピーダンス32Ω〜<br>●光デジタル音声出力端子：×1<br>●LAN端子：LANポート(RJ45)×1 ※データ放送用<br>●商品サイズ(cm)：幅約73.34×奥行約19.32×高さ約47.4<br>●消費電力(待機電力)：50W(0.5W)<br>●付属品：リモコン、リモコン用単4乾電池(テスト用)×2個、miniB-CASカード、miniB-CASカードスロットカバー、スタンド×2個、スタンド固定ネジ×2個、取扱説明書、保証書、電源コード",
#             "headLine": "irsale_tv",
#             "url": "https://store.shopping.yahoo.co.jp/petkan/572716.html",
#             "inStock": true,
#             "code": "petkan_572716",
#             "condition": "new",
#             "imageId": "petkan_572716",
#             "image": { "small": "https://item-shopping.c.yimg.jp/i/c/petkan_572716", "medium": "https://item-shopping.c.yimg.jp/i/g/petkan_572716" },
#             "review": { "rate": 4.58, "count": 59, "url": "https://shopping.yahoo.co.jp/review/item/list?store_id=petkan&page_key=572716" },
#             "affiliateRate": 1,
#             "price": 22800,
#             "premiumPrice": 22800,
#             "premiumPriceStatus": false,
#             "premiumDiscountType": null,
#             "premiumDiscountRate": null,
#             "priceLabel": { "taxable": true, "defaultPrice": 22800, "discountedPrice": null, "fixedPrice": null, "premiumPrice": null, "periodStart": 1646023260, "periodEnd": 1646967600 },
#             "point": { "amount": 228, "times": 1, "bonusAmount": 0, "bonusTimes": 0, "premiumAmount": 228, "premiumTimes": 1, "premiumBonusAmount": 0, "premiumBonusTimes": 0 },
#             "shipping": { "code": 2, "name": "送料無料" },
#             "genreCategory": { "id": 49520, "name": "液晶テレビ、薄型テレビ", "depth": 4 },
#             "parentGenreCategories": [
#                 { "depth": 1, "id": 2504, "name": "テレビ、オーディオ、カメラ" },
#                 { "depth": 2, "id": 635, "name": "テレビ、映像機器" },
#                 { "depth": 3, "id": 49514, "name": "テレビ" }
#             ],
#             "brand": { "id": 50490, "name": "LUCA（アイリスオーヤマ）" },
#             "parentBrands": [
#                 { "id": 1, "name": "ブランド" },
#                 { "id": 113, "name": "IRIS OHYAMA" }
#             ],
#             "janCode": "4967576501026",
#             "payment": "1 2 4 16 256 512 1024 4096 8192",
#             "releaseDate": null,
#             "seller": {
#                 "sellerId": "petkan",
#                 "name": "megastore PayPayモール店",
#                 "url": "https://paypaymall.yahoo.co.jp/store/petkan/top/",
#                 "isBestSeller": true,
#                 "isPMallSeller": true,
#                 "review": { "rate": 4.43, "count": 70187 },
#                 "imageId": "petkan_1"
#             },
#             "delivery": { "area": "13", "deadLine": 24, "day": 2 }
#         }
#     ]
# }
